CREATE TABLE `gaming`.`potion` (
  `ID` INT NOT NULL COMMENT 'Id of the Potion',
  `ADJUST_VALUE` DOUBLE NOT NULL DEFAULT 0 COMMENT 'A value that is added to the eventual value of the potion.',
  `ARMOR_CLASS` BIT(1) NULL COMMENT 'Does the potion affect armor class.',
  `ARMOR_CLASS_VALUE` INT NOT NULL COMMENT 'If potion affects armor class, how much does it adjust it.',
  `BASE_COLOR` BIT(1) NULL COMMENT 'Base color is used to help determine the color of the potion.',
  `BASE_VALUE` DOUBLE NOT NULL DEFAULT 0 COMMENT 'The base value of the potion. This is usually not used in the calculation of the potion.',
  `CURSED` BIT(1) NOT NULL DEFAULT 0 COMMENT 'Determines if the potion is cursed.',
  `DESCRIPTION` VARCHAR(2000) NULL COMMENT 'Description of how the potion works.',
  `DOSES` INT NOT NULL DEFAULT 1 COMMENT 'How many doses are in the potion vial.',
  `DURATION` INT NULL COMMENT 'How long the potion lasts, in rounds.',
  `EXPERIENCE_VALUE` INT NOT NULL COMMENT 'The experience points awarded for using this potion.',
  `FREQUENCY` BIT(1) NOT NULL COMMENT 'Availabilty of the potion.',
  `ITEM_CATEGORY` BIT(1) NOT NULL COMMENT 'Used to determine what category the potion falls under. All potions are under Potion category.',
  `MAGICAL` BIT(1) NOT NULL DEFAULT 0 COMMENT 'Determines if it is magical. Not all potions are magical.',
  `NAME` VARCHAR(255) NOT NULL COMMENT 'The name of the potion.',
  `RESOURCE_LIBRARY_ID` INT NOT NULL COMMENT 'The id of the resouce (book, created) that contains the potion.',
  `RESOURCE_LIBRARY_PAGE` INT NULL COMMENT 'What  page the potion appears in the resource book it is in.',
  `ROGUE_SKILL` BIT(1) NULL COMMENT 'Determines if the potion affects saving throws.',
  `ROGUE_SKILL_ID` INT NULL COMMENT 'The id of the saving throw that the potion affects.',
  `ROGUE_SKILL_VALUE` DOUBLE NULL COMMENT 'If the potions affects a saving throw, how much does it affect.',
  `SAVING_THROW` BIT(1) NULL COMMENT 'Determines if the poition affects saving throws.',
  `SAVING_THROW_ID` INT NULL COMMENT 'The id of the saving throw that the potion affects.',
  `SAVING_THROW_VALUE` INT NULL COMMENT 'If the potion affects a saving throw, what is the value.',
  `STACKABLE` BIT(1) NOT NULL DEFAULT 0 COMMENT 'Is the potion stackable',
  `VOLUME` DOUBLE NULL COMMENT 'How much space the potion takes up.',
  `WEIGHT` DOUBLE NULL DEFAULT 0.5 COMMENT 'How much does the potion weigh.',
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC))
COMMENT = 'This holds all magic potions including potions, elixirs, oils, and so on.';
